export const IS_LOGGED_IN = 'IS_LOGGED_IN';

export const PAGE_TITLE = 'PAGE_TITLE';

export const CLEAR_STORE_DATA = 'CLEAR_STORE_DATA';

export const LOADING = 'LOADING';

export const CUSTOM_LOADING = 'CUSTOM_LOADING';

export const ALERT = 'ALERT';

export const RESET_INTERACTION = 'RESET_INTERACTION';

export const STORE_COUNTER = "STORE_COUNTER";

export const LOG_IN_NOW = "LOG_IN_NOW";

export const FETCH_PRODUCTS = "FETCH_PRODUCTS";

export const SAVE_CATEGORIES = "SAVE_CATEGORIES";

export const SAVE_CATEGORY_PRODUCTS = "SAVE_CATEGORY_PRODUCTS";

export const SAVE_BESTSELLING_PRODUCTS = "SAVE_BESTSELLING_PRODUCTS";

export const SAVE_RECOMMENDED_PRODUCTS = "SAVE_RECOMMENDED_PRODUCTS";

export const CLEAR_PRODUCTS_DATA = "CLEAR_PRODUCTS_DATA";


//CART FUNTIOANALITY ACTIONS
export const ADD_TO_CART = "ADD_TO_CART";

export const ADD_TO_CART_WITH_QTY = "ADD_TO_CART_WITH_QTY";

export const UPDATE_CART = "UPDATE_CART";

export const UPDATE_QTY = "UPDATE_QTY";

export const UPDATE_PRODUCT_WITH_QTY = "UPDATE_PRODUCT_WITH_QTY";

export const CHANGE_QTY = "CHANGE_QTY";

export const DECREASE_QTY = "DECREASE_QTY";

export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";

export const CLEAR_CART = "CLEAR_CART";

export const UPDATE_CART_PRICE = "UPDATE_CART_PRICE";

//Checkout Actions
export const PREPARE_CHECKOUT = "PREPARE_CHECKOUT";

export const UPDATE_PAYMENT_MODE = "UPDATE_PAYMENT_MODE";

export const UPDATE_CARD_NO = "UPDATE_CARD_NO";

export const SAVE_STATUS = "SAVE_STATUS";

export const SAVE_FOR_BILLING = "SAVE_FOR_BILLING";

export const CLEAR_BILLING = "CLEAR_BILLING";

export const SAVE_INVOICE = "SAVE_INVOICE";


//Customer Actions
export const CALCULATE_TENDER = "CALCULATE_TENDER";

export const UPDATE_CPHONE = "UPDATE_CPHONE";

export const UPDATE_CNAME = "UPDATE_CNAME";

export const UPDATE_SALES_EXE = "UPDATE_SALES_EXE";

export const CLEAR_CUSTOMER = "CLEAR_CUSTOMER";

export const UPDATE_REWARD_PKG_ID = "UPDATE_REWARD_PKG_ID";

export const UPDATE_MEMBER_NO = "UPDATE_MEMBER_NO";

export const UPDATE_PAID_AMT = "UPDATE_CUSTOMER_PAID_AMT";

export const UPDATE_CREDIT_AMT = "UPDATE_CUSTOMER_CREDIT_AMT";


//Other Payment Actions
export const OTHER_PAYMENT_CASH = "OTHER_PAYMENT_CASH";

export const OTHER_PAYMENT_CARD = "OTHER_PAYMENT_CARD";

export const OTHER_PAYMENT_CARD_NO = "OTHER_PAYMENT_CARD_NO";

export const OTHER_PAYMENT_OTHER = "OTHER_PAYMENT_OTHER";

export const OTHER_PAYMENT_OTHER_TYPE = "OTHER_PAYMENT_OTHER_TYPE";

export const CLEAR_OTHER_PAYMENT = "CLEAR_OTHER_PAYMENT";

//OFFLINE ORDER
export const SAVE_OFFLINE_ORDER = "SAVE_OFFLINE_ORDER";

export const REMOVE_OFFLINE_ORDER = "REMOVE_OFFLINE_ORDER";


//SUSPEND CART FUNTIOANALITY ACTIONS
export const SUSPEND_CART = "SUSPEND_CART";

export const RESTORE_SUSPENDED_CART_PRODUCT = "RESTORE_SUSPENDED_CART_PRODUCT";

export const REMOVE_FROM_SUSPENDED_CART = "REMOVE_FROM_SUSPENDED_CART";

export const CLEAR_SUSPENDED_CART = "CLEAR_SUSPENDED_CART";


//RETURN FUNTIOANALITY ACTIONS
export const RETURN_IS_ACTIVE = "RETURN_IS_ACTIVE";

export const SAVE_RETURNING_INVOICE_NO = "SAVE_RETURNING_INVOICE_NO";

export const LOAD_RETURNING_PRODUCTS = "LOAD_RETURNING_PRODUCTS";

export const CLEAR_RETURNING_PRODUCTS = "CLEAR_RETURNING_PRODUCTS";

export const START_RULE_CALCULATION = "START_RULE_CALCULATION";

export const SWITCH_RETURNING_PRODUCTS = "SWITCH_RETURNING_PRODUCTS";

export const SWITCH_COMPLETE_RETURN = "SWITCH_COMPLETE_RETURN";

//MANUAL DISCOUNT FUNTIOANALITY ACTIONS
export const OPEN_DISCOUNT_BOX = "OPEN_DISCOUNT_BOX";

export const APPLY_COUPON = "APPLY_COUPON";

export const IS_COUPON_APPLIED = "IS_COUPON_APPLIED";

export const APPLY_FLAT_OFF = "APPLY_FLAT_OFF";

export const APPLY_PERCENT_OFF = "APPLY_PERCENT_OFF";

export const CLEAR_APPLIED_DISCOUNT = "CLEAR_APPLIED_DISCOUNT";

export const SAVE_COUPON_DATA = "SAVE_COUPON_DATA";

export const SPOT_APPLY_DISCOUNT = "SPOT_APPLY_DISCOUNT";

export const IS_ADDITIONAL_APPLIED = "IS_ADDITIONAL_APPLIED";



//EDIT FUNTIOANALITY ACTIONS
export const EDIT_IS_ACTIVE = "EDIT_IS_ACTIVE";

export const SAVE_EDIT_INVOICE_NO = "SAVE_EDIT_INVOICE_NO";

export const LOAD_EDIT_PRODUCTS = "LOAD_EDIT_PRODUCTS";

export const CLEAR_EDIT_PRODUCTS = "CLEAR_EDIT_PRODUCTS";


//Open Close REGISTER PAGE
export const SAVE_DENOMINATION = "SAVE_DENOMINATION";

export const CLEAR_OPEN_CLOSE_REGISTER = "CLEAR_OPEN_CLOSE_REGISTER";

export const FETCH_OPEN_CLOSE_REGISTER = "FETCH_OPEN_CLOSE_REGISTER";

export const SAVE_OPEN_CLOSE_REGISTER = "SAVE_OPEN_CLOSE_REGISTER";

//SALES RECORD PAGE
export const LOAD_SALES_RECORD = "LOAD_SALES_RECORD";


//SEND STOCK REQUEST
export const SEND_STOCK_REQUEST = "SEND_STOCK_REQUEST";


//CANCEL INVOICE ACTIONS
export const OPEN_CANCEL_POPUP = "OPEN_CANCEL_POPUP";

export const LOAD_CANCEL_INVOICE_DATA = "LOAD_CANCEL_INVOICE_DATA";

export const SAVE_CANCEL_INVOICE_DATA = "SAVE_CANCEL_INVOICE_DATA";

export const CLEAR_CANCEL_INVOICE_DATA = "CLEAR_CANCEL_INVOICE_DATA";


//Customer Redeem Actions
export const LOAD_CUST_REC = "LOAD_CUST_REC";

export const CUST_RED_TOTAL = "CUST_RED_TOTAL";

export const CUST_RED_AMOUNT = "CUST_RED_AMOUNT";

export const COUPON_CHECK = "COUPON_CHECK";

export const CLEAR_CUSTOMER_DATA = 'CLEAR_CUSTOMER_DATA';


//MULTIPLE PRICE ACTIONS
export const OPEN_PRICE_POPUP = "OPEN_PRICE_POPUP";

export const SAVE_MULTI_PRICE_PRODUCT = "SAVE_MULTI_PRICE_PRODUCT";

export const SAVE_SELECTED_PRICE = "SAVE_SELECTED_PRICE";

export const CLEAR_MULTI_PRICE_DATA = "CLEAR_MULTI_PRICE_DATA";


//ADMIN LOGIN ACTIONS
export const TOOGLE_LOCATION_POPUP = "TOOGLE_LOCATION_POPUP";

export const SET_LOCATION = "SET_LOCATION";

export const UPDATE_LOCATION_ID = "UPDATE_LOCATION_ID";

export const UPDATE_LOCATION_NAME = "UPDATE_LOCATION_NAME";

export const CLEAR_COUNTER_DATA = "CLEAR_COUNTER_DATA";

export const DUMMY_BILL = "DUMMY_BILL";


//CREATE PRODUCT ACTIONS
export const TOOGLE_CREATE_PRODUCT = "TOOGLE_CREATE_PRODUCT";


//CREDIT FUNTIOANALITY ACTIONS
export const TOGGLE_CREDIT_POPUP = "TOGGLE_CREDIT_POPUP";

export const LOAD_CREDIT_PRODUCTS = "LOAD_CREDIT_PRODUCTS";

export const CLEAR_CREDIT_PRODUCTS = "CLEAR_CREDIT_PRODUCTS";

export const TOGGLE_CREDIT_SUCCESS_POPUP = "TOGGLE_CREDIT_SUCCESS_POPUP";

export const UPDATE_CREDIT_INVOICE = "UPDATE_CREDIT_INVOICE";

export const SAVE_CREDIT_RES = "SAVE_CREDIT_RES";

export const CLEAR_CREDIT_DATA = "CLEAR_CREDIT_DATA";


//MANUAL QTY ENTRY ACTIONS
export const OPEN_QTY_POPUP = "OPEN_QTY_POPUP";

export const CLEAR_MANUAL_QTY_DATA = "CLEAR_MANUAL_QTY_DATA";

export const SAVE_QTY_PRODUCT = "SAVE_QTY_PRODUCT";